In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/flats.csv')
print(df.shape)
df.sample(5)

(3017, 20)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1089,3 BHK Flat in Sector 70A Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,AIPL The Peaceful Homes3.9 ★,2.4 Crore,"₹ 11,162/sq.ft.",Super Built up area 2150(199.74 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"11floor, Sector 70A Gurgaon, Gurgaon, Haryana",11st of 30 Floors,South-West,1 to 5 Year Old,"['Airia Mall', 'Golf Corse Ext. Rd.', 'Nationa...",Aipl the peaceful homes is one of the most pop...,"['5 Fan', '3 Geyser', '6 Light', '3 AC', 'No B...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ...",L68419948
108,2 BHK Flat in Sector 95 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Ramsons Kshitij3.7 ★,31.5 Lac,"₹ 4,500/sq.ft.",Super Built up area 700(65.03 sq.m.)Carpet are...,2 Bedrooms,2 Bathrooms,1 Balcony,Others,"Sector 95 Gurgaon, Gurgaon, Haryana",8th of 14 Floors,NaN,1 to 5 Year Old,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...","Fully furnished 2bhk apartment, on main pataud...","['1 Water Purifier', '3 Fan', '1 Fridge', '1 D...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area4 out of 5', 'Amenities4 out of 5'...",F54906058
660,3 BHK Flat in Sector 79 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Mapsko Mount Ville4.1 ★,1.3 Crore,"₹ 8,724/sq.ft.",Super Built up area 1490(138.43 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,Store Room,"876, Sector 79 Gurgaon, Gurgaon, Haryana",19th of 30 Floors,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",3 bhk flat available for sell in mapsko mount ...,"['3 Wardrobe', '1 Stove', '1 Modular Kitchen',...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of...",O69444490
228,2 BHK Flat in Sector 37D Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Ramprastha The Edge Towers3.5 ★,71 Lac,"₹ 5,420/sq.ft.",Super Built up area 1310(121.7 sq.m.)Built Up ...,2 Bedrooms,2 Bathrooms,3 Balconies,Others,"Gurgaon, Sector 37D Gurgaon, Gurgaon, Haryana",10th of 22 Floors,South-East,0 to 1 Year Old,"['MDS Public School', 'St Pauls School', 'Sunc...",Residential apartment for sell.Located in sect...,[],"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area4 out of 5', 'Amenities4 out of 5'...",W38206361
1464,2 BHK Flat in Sector 74 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,M3M Skywalk,1.52 Crore,"₹ 13,342/sq.ft.",Super Built up area 1400(130.06 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,3 Balconies,Store Room,"1504, Sector 74 Gurgaon, Gurgaon, Haryana",6th of 30 Floors,South-East,1 to 5 Year Old,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...",Located in the popular residential address of ...,[],"['Centrally Air Conditioned', 'Water purifier'...",NaN,S69823246

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   str
 1   link             3017 non-null   str
 2   society          3016 non-null   str
 3   price            3007 non-null   str
 4   area             3004 non-null   str
 5   areaWithType     3008 non-null   str
 6   bedRoom          3008 non-null   str
 7   bathroom         3008 non-null   str
 8   balcony          3008 non-null   str
 9   additionalRoom   1694 non-null   str
 10  address          3002 non-null   str
 11  floorNum         3006 non-null   str
 12  facing           2127 non-null   str
 13  agePossession    3007 non-null   str
 14  nearbyLocations  2913 non-null   str
 15  description      3008 non-null   str
 16  furnishDetails   2203 non-null   str
 17  features         2594 non-null   str
 18  rating           2676 non-null   str
 19  property_id      3008 non-null   str
dtypes: str(20)
memory usage: 5.8 MB

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [6]:
# dropping columns {'link','property_id'}
df.drop(columns=['link','property_id'],inplace=True)

In [7]:
df.shape

(3017, 18)

In [8]:
# correcting column name of area, changing it to price_per_sqft
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [9]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                             73
Tulip Violet4.3 ★                            40
Shapoorji Pallonji Joyville Gurugram4.0 ★    39
Signature Global Park4.0 ★                   36
Shree Vardhman Victoria3.8 ★                 35
                                             ..
Uphar lakshya homes                           1
Godrej Aria , sector 79 , Gurgaon             1
M3M Woodshire                                 1
Krishna appartment                            1
Spire Woods Now Ananda by Alpha corp          1
Name: count, Length: 638, dtype: int64

In [10]:
df['society'].value_counts().shape

(638,)

In [11]:
# removing ratings from the names of the society
df['society'] = df['society'].str.replace(r'\d+(\.\d+)?\s*★?', '', regex=True).str.strip()

In [12]:
df['society'].value_counts()

society
Tulip Violet                            75
SS The Leaf                             74
Shapoorji Pallonji Joyville Gurugram    45
Signature Global Park                   42
DLF New Town Heights                    38
                                        ..
ss residency                             1
Uphar lakshya homes                      1
Godrej Aria , sector , Gurgaon           1
Krishna appartment                       1
Spire Woods Now Ananda by Alpha corp     1
Name: count, Length: 602, dtype: int64

In [13]:
df['price'].value_counts()

price
1.25 Crore    79
1.1 Crore     61
1.4 Crore     60
1.2 Crore     59
1.5 Crore     59
              ..
26.9 Lac       1
26.5 Lac       1
73.53 Lac      1
89.77 Lac      1
62.5 Lac       1
Name: count, Length: 439, dtype: int64

In [14]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,The New People Apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1644,4 BHK Flat in Sector 50 Gurgaon,SS Hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1972,1 BHK Flat in Sector 31 Gurgaon,Raheja Atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2054,2 BHK Flat in Sector 79 Gurgaon,Supertech Araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2357,2 BHK Flat in Sector 37D Gurgaon,The Millennia,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2522,2 BHK Flat in Sector 95A Gurgaon,The Roselia,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2549,3 BHK Flat in Sector-2 Sohna,Supertech Hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2640,2 BHK Flat in Sector 95A Gurgaon,The Roselia,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2959,3 BHK Flat in Sector 104 Gurgaon,Godrej Summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2972,4 BHK Flat in Gwal Pahari,Krrish Provence Estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2973,4 BHK Flat in Sector 95 Gurgaon,Sidhartha NCR One Phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [15]:
# removing those rows which have Nan and "Price on Request" in price column.
df = df.dropna(subset=['price'])
df = df[df['price'] != 'Price on Request']

In [16]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [17]:
def convert_price(price):
    price = str(price).strip()
    if('Lac' in price):
        price = price.replace('Lac','').strip()
        return round(float(price)/100,2)
    
    elif('Crore' in price):
        price = price.replace('Crore','').strip()
        return round(float(price),2)
    else:
        pass

In [18]:
df['price'] = df['price'].apply(convert_price)

In [19]:
df.rename(columns={'price':'price(cr)'},inplace=True)

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   str
 1   society          2995 non-null   str
 2   price(cr)        2996 non-null   float64
 3   price_per_sqft   2996 non-null   str
 4   areaWithType     2996 non-null   str
 5   bedRoom          2996 non-null   str
 6   bathroom         2996 non-null   str
 7   balcony          2996 non-null   str
 8   additionalRoom   1692 non-null   str
 9   address          2990 non-null   str
 10  floorNum         2994 non-null   str
 11  facing           2122 non-null   str
 12  agePossession    2995 non-null   str
 13  nearbyLocations  2905 non-null   str
 14  description      2996 non-null   str
 15  furnishDetails   2200 non-null   str
 16  features         2589 non-null   str
 17  rating           2668 non-null   str
dtypes: float64(1), str(17)
memory usage: 5.4 MB

In [21]:
df.sample()

,property_name,society,price(cr),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
449,3 BHK Flat in Sector 67 Gurgaon,MM Merlin,3.5,"₹ 14,583/sq.ft.",Super Built up area 2400(222.97 sq.m.)Carpet a...,3 Bedrooms,4 Bathrooms,3 Balconies,"Servant Room,Store Room","1701, Sector 67 Gurgaon, Gurgaon, Haryana",17th of 25 Floors,South-East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extension Road', '...",This 3 bhk apartment is available for sale in ...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."

In [22]:
df['price_per_sqft'] = df['price_per_sqft'].str.replace(r'[₹,/sq.fit.]','',regex=True).str.strip().astype(float)

In [23]:
df.sample()

,property_name,society,price(cr),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1622,3 BHK Flat in Sector 67A Gurgaon,Ireo The Corridors,1.8,14658.0,Super Built up area 1921(178.47 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,"Servant Room,Store Room","A-000, Sector 67A Gurgaon, Gurgaon, Haryana",6th of 19 Floors,North,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Paras Trini...",Brokers please excuse\n3 bhk +servant room + s...,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'F...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [24]:
df['price_per_sqft'].dtype

dtype('float64')

In [25]:
df.sample(10)

,property_name,society,price(cr),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1993,2 BHK Flat in Sector 67 Gurgaon,Shree Vardhman Mantra,0.56,7000.0,Carpet area: 800 (74.32 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sector 67 Gurgaon, Gurgaon, Haryana",8th of 13 Floors,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Airia Mall', '...",Residential apartment for sell.The property co...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area4 out of 5', 'Construction4 out of..."
1106,3 BHK Flat in Nirvana Country,The Close South,3.10,12444.0,Super Built up area 2491(231.42 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"4th, Nirvana Country, Gurgaon, Haryana",4th of 18 Floors,North-East,5 to 10 Year Old,"['Fresco Market', 'Emerald Plaza', 'Tagore Pub...",The close south is one of gurgaon's most sough...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."
2294,2 BHK Flat in Sector 81 Gurgaon,Vipul Lavanya,0.60,6666.0,Super Built up area 900(83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",Ground of 15 Floors,NaN,By 2023,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk apartmen...,[],NaN,"['Green Area5 out of 5', 'Construction4.5 out ..."
2698,3 BHK Flat in Sector 113 Gurgaon,La Vida by Tata Housing,1.93,12222.0,Super Built up area 1579(146.69 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 113 Gurgaon , Gurgaon, Haryana",8th of 14 Floors,NaN,By 2023,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",It is a part of la vida by tata housing. The a...,[],NaN,NaN
188,1 BHK Flat in Block A Surya Vihar,Shree shyam residency,0.22,4731.0,Super Built up area 585(54.35 sq.m.)Carpet are...,1 Bedroom,1 Bathroom,1 Balcony,NaN,"Plot 833 Flat 202, Block A Surya Vihar, Gurgao...",2nd of 3 Floors,East,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...",This property is adjecent to sector 4 and on s...,"['1 Wardrobe', '1 Fan', '1 Light', '1 Modular ...",NaN,NaN
774,3 BHK Flat in Sector 83 Gurgaon,Vatika Gurgaon,1.18,6801.0,Super Built up area 1735(161.19 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 83 Gurgaon, Gurgaon, Haryana",14th of 18 Floors,North,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Vatika gurgaon 21 is one of gurgaon's most sou...,NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M...","['Green Area5 out of 5', 'Construction4.5 out ..."
2451,3 BHK Flat in Sector 92 Gurgaon,Sare Green Parc,0.75,4820.0,Built Up area: 1556 (144.56 sq.m.)Carpet area:...,3 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 92, Sector 92 Gurgaon, Gurgaon, Haryana",16th of 16 Floors,NaN,undefined,"['Huda city centre metro station', 'Iffco chow...","2 bath, unfurnished, 16th floor (Of 19), sare ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1100,4 BHK Flat in Sector 60 Gurgaon,Ireo Skyon,3.60,12815.0,Super Built up area 2809(260.96 sq.m.)Carpet a...,4 Bedrooms,5 Bathrooms,3 Balconies,Servant Room,"Sector 60 Gurgaon, Gurgaon, Haryana",24th of 39 Floors,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...","This 4 bhk flat is located in ireo skyon, whic...","['7 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
1023,4 BHK Flat in Sector 72 Gurgaon,Tata Primanti,5.00,11363.0,Super Built up area 4400(408.77 sq.m.)Built Up...,4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room,Store Room","Ef/7c, Sector 72 Gurgaon, Gurgaon, Haryana",2nd of 40 Floors,North-East,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This beautiful 4 bhk flat in sector 72 gurgaon...,"['4 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
1785,2 BHK Flat in Sector 84 Gurgaon,Antriksh Heights,0.73,6083.0,Super Built up area 1200(111.48 sq.m.)Carpet a...,2 Bedrooms,2 Bathrooms,3+ Balconies,"Study Room,Pooja Room,Store Room","Sector 84 Gurgaon, Gurgaon, Haryana",4th of 19 Floors,North-West,1 to 5 Year Old,"['Old Bengali Market', 'MatriKiran High School...",This property is very good becouse of itsattre...,NaN,"['Water purifier', 'Centrally Air Conditioned'...","['Green Area4.5 out of 5', 'Construction3.5 ou..."

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   str
 1   society          2995 non-null   str
 2   price(cr)        2996 non-null   float64
 3   price_per_sqft   2996 non-null   float64
 4   areaWithType     2996 non-null   str
 5   bedRoom          2996 non-null   str
 6   bathroom         2996 non-null   str
 7   balcony          2996 non-null   str
 8   additionalRoom   1692 non-null   str
 9   address          2990 non-null   str
 10  floorNum         2994 non-null   str
 11  facing           2122 non-null   str
 12  agePossession    2995 non-null   str
 13  nearbyLocations  2905 non-null   str
 14  description      2996 non-null   str
 15  furnishDetails   2200 non-null   str
 16  features         2589 non-null   str
 17  rating           2668 non-null   str
dtypes: float64(2), str(16)
memory usage: 5.3 MB

In [27]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     943
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [28]:
df['bedRoom'].isnull().sum()

np.int64(0)

In [29]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype(int)

In [30]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1043
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [31]:
df['bathroom'].isnull().sum()

np.int64(0)

In [32]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype(int)

In [33]:
df['balcony'].value_counts()

balcony
3 Balconies     973
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [34]:
df['balcony'].isnull().sum()

np.int64(0)

In [35]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [36]:
df.sample(5)

,property_name,society,price(cr),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2475,3 BHK Flat in Sector 92 Gurgaon,DLF Garden City Floors,1.70,8588.0,Super Built up area 1630(151.43 sq.m.),3,4,2,NaN,"Sector 92 Gurgaon, Gurgaon, Haryana",1st of 4 Floors,NaN,Dec 2024,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH-...",We are the proud owners of this 3 bhk apartmen...,[],NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1185,2 BHK Flat in Sector 81 Gurgaon,Signature Global Synera,0.50,6802.0,Super Built up area 735(68.28 sq.m.)Built Up a...,2,2,3,NaN,"Ddd, Sector 81 Gurgaon, Gurgaon, Haryana",6th of 12 Floors,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...",This lovely 2 bhk apartment/flat in sector 81 ...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Construction3 out of..."
2536,2 BHK Flat in Sector 63A Gurgaon,Signature Global City A,1.40,11336.0,Carpet area: 1235 (114.74 sq.m.),2,2,2,Others,"Sector 63A Gurgaon, Gurgaon, Haryana",3rd of 4 Floors,East,Jul 2024,"['Sector 54 Chowk Metro Station', 'Paras Trini...",This is located at golf course extension road,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2150,3 BHK Flat in Sector 104 Gurgaon,Hero Homes,1.35,9565.0,Super Built up area 1359(126.26 sq.m.)Carpet a...,3,2,2,NaN,"Sector 104 Gurgaon, Gurgaon, Haryana",18th of 35 Floors,East,Within 6 months,"['Basai Metro Station', 'HUDA Market', 'Dwarka...",Hero homes is one of the most popular destinat...,"['1 Fan', '1 Exhaust Fan', '1 Light', 'No AC',...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1940,2 BHK Flat in Sector 102 Gurgaon,ROF Aalayas,0.45,8404.0,Super Built up area 597(55.46 sq.m.)Carpet are...,2,2,1,NaN,"Sector 102 Gurgaon, Gurgaon, Haryana",14th of 14 Floors,North,1 to 5 Year Old,"['HUDA Metro Station', 'Idea Cosmic Plaza', 'G...",Genuine wooden work with lifetime warranty \nI...,"['1 Water Purifier', '3 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."

In [37]:
df.fillna({'additionalRoom':'Not available'},inplace=True)
df.sample(5)

,property_name,society,price(cr),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
297,3 BHK Flat in DLF Phase 5,DLF Carlton Estate,2.00,14214.0,Super Built up area 1407(130.71 sq.m.),3,3,2,Not available,"DLF Phase 5, Gurgaon, Haryana",5th of 19 Floors,South-West,5 to 10 Year Old,"['Sector 53-54', 'South Point Mall', 'United C...",This is your chance to own a 3 bhk residential...,"['2 Wardrobe', '1 Sofa', '2 Geyser', '2 AC', '...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Connectivity5 out of 5', 'Management4.5 out ..."
464,4 BHK Flat in Sector 69 Gurgaon,Tulip Purple,1.80,9000.0,Super Built up area 2400(222.97 sq.m.)Built Up...,4,5,3+,Servant Room,"Sector 69 Gurgaon, Gurgaon, Haryana",4th of 12 Floors,North-East,1 to 5 Year Old,"['Sector 55-56 metro station', 'Omaxe Gurgaon ...",Very nice property at nice location at cheaper...,"['4 Wardrobe', '1 Modular Kitchen', 'No AC', '...","['Water purifier', 'Security / Fire Alarm', 'F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1673,4 BHK Flat in Sector 86 Gurgaon,DLF New Town Heights,1.55,6578.0,Super Built up area 2356(218.88 sq.m.)Carpet a...,4,4,3+,"Pooja Room,Servant Room","Sector 86 Gurgaon, Gurgaon, Haryana",12nd of 22 Floors,North-East,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...","Sun facing, park facing, best location for sal...","['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ..."
1652,2 BHK Flat in Sector 90 Gurgaon,Shree Vardhman Flora,0.65,4814.0,Super Built up area 1350(125.42 sq.m.),2,2,3,Study Room,"Sector-90,gurgaon, Sector 90 Gurgaon, Gurgaon,...",3rd of 13 Floors,North,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",This 2 bhk flat is located in shree vardhman f...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
476,3 BHK Flat in Sector 48 Gurgaon,Parsvnath Green Ville,1.60,8376.0,Super Built up area 1910(177.44 sq.m.)Built Up...,3,3,3+,Others,"801, Sector 48 Gurgaon, Gurgaon, Haryana",8th of 11 Floors,North,10+ Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",This lovely 3 bhk apartment/flat in sector 48 ...,"['8 Fan', '1 Exhaust Fan', '3 Geyser', '3 Ligh...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."

In [38]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors      74
3rd   of 4 Floors      71
4th   of 4 Floors      62
1st   of 4 Floors      61
12nd   of 14 Floors    49
                       ..
14th   of 25 Floors     1
3rd   of 7 Floors       1
Ground of 22 Floors     1
13rd   of 34 Floors     1
23rd   of 36 Floors     1
Name: count, Length: 550, dtype: int64

In [39]:
df['floorNum'].isnull().sum()

np.int64(2)

In [40]:
df[df['floorNum'].isnull()]

,property_name,society,price(cr),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,Experion Heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,Not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2766,2 BHK Flat in Sector 78 Gurgaon,NaN,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,Not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [41]:
df['floorNum'] = (
    df['floorNum']
    .str.split(' ').str.get(0)
    .replace('Ground','0')
    .str.replace('Basement','-1')
    .str.replace('Lower','0')
    .str.replace(r'(st|nd|rd|th)','',regex=True).str.strip()
)
df.sample(5)

,property_name,society,price(cr),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1772,3 BHK Flat in Sector 69 Gurgaon,Tulip Violet,1.36,8618.0,Super Built up area 1578(146.6 sq.m.),3,3,2,Pooja Room,"Sector 69 Gurgaon, Gurgaon, Haryana",12,West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This beautiful 3 bhk flat in sector 69 gurgaon...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
1627,4 BHK Flat in Sector 43 Gurgaon,Millenium Bajrang Society,2.50,9433.0,Super Built up area 2650(246.19 sq.m.),4,4,3+,Not available,"Sector 43 Gurgaon, Gurgaon, Haryana",2,South,1 to 5 Year Old,"['Sector 42-43 metro station', 'Sector 53-54 m...",4bhk flat is available for sale in bajrang cgh...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
268,3 BHK Flat in Sector 70 Gurgaon,Unitech Vistas,0.99,6325.0,Super Built up area 1565(145.39 sq.m.),3,4,2,Not available,"Sector 70 Gurgaon, Gurgaon, Haryana",11,NaN,By 2024,"['Airia Mall', 'Delhi Ajmer Highway', 'Sohna R...",We are the proud owners of this 3 bhk apartmen...,[],NaN,"['Environment4 out of 5', 'Safety3.5 out of 5'..."
2546,2 BHK Flat in Sector 93 Gurgaon,Signature Global Orchard Avenue,0.40,7359.0,Carpet area: 543.53 (50.5 sq.m.),2,2,2,Not available,"Sector 93 Gurgaon, Gurgaon, Haryana",11,NaN,0 to 1 Year Old,"['JMS Crosswalk Mall', 'Reliance Trends Newtow...","Situated in sector-93 gurgaon, gurgaon, signat...","['1 Fan', '1 Exhaust Fan', '1 Geyser', '5 Ligh...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area4 out of 5', 'Construction4 out of..."
941,3 BHK Flat in Sector 91 Gurgaon,TARC Maceo,1.50,6465.0,Super Built up area 2320(215.54 sq.m.)Carpet a...,3,4,3+,"Study Room,Servant Room","Sector 91 Gurgaon, Gurgaon, Haryana",3,North-West,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",This 3 bhk apartment is available for sale in ...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."

In [42]:
df['facing'].value_counts()

facing
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [43]:
df['facing'].isnull().sum()

np.int64(874)

In [44]:
df.fillna({'facing':'NA'},inplace=True)
df.sample(5)

,property_name,society,price(cr),price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1489,3 BHK Flat in Sector 79 Gurgaon,Godrej,1.28,8504.0,Super Built up area 1505(139.82 sq.m.),3,3,3,Not available,"Aa1, Sector 79 Gurgaon, Gurgaon, Haryana",7,North-East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...",This beautiful 3 bhk flat in sector 79 gurgaon...,NaN,"['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of..."
2255,2 BHK Flat in Sohna,kamal residence,0.40,7633.0,Carpet area: 524 (48.68 sq.m.),2,2,1,Others,"Flat No 7, Sohna, Gurgaon, Haryana",0,North-East,0 to 1 Year Old,NaN,Good maintain nd good conditions,"['2 Wardrobe', '5 Fan', '1 Geyser', '12 Light'...","['Security / Fire Alarm', 'Lift(s)', 'Water St...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2829,4 BHK Flat in Sector 85 Gurgaon,SS The Leaf,2.70,7754.0,Super Built up area 3482(323.49 sq.m.),4,4,3+,Not available,"Sector 85 Gurgaon, Gurgaon, Haryana",23,NA,0 to 1 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","Situated in sector 85 gurgaon, ss the leaf is ...",[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management4 out of 5', 'Green Area4.5 out of..."
210,2 BHK Flat in Sector 37D Gurgaon,Signature Global the Millennia,0.55,9166.0,Super Built up area 600(55.74 sq.m.),2,2,3,Not available,"Sector 37D Gurgaon, Gurgaon, Haryana",3,NA,0 to 1 Year Old,"['Jharsha Chowk', 'Hero Honda Chowk', 'Rajiv C...",We are the proud owners of this 2 bhk apartmen...,[],NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2966,3 BHK Flat in Sector 68 Gurgaon,Pareena Mi Casa,1.85,9310.0,Super Built up area 1987(184.6 sq.m.),3,3,3+,Not available,"Sector 68 Gurgaon, Gurgaon, Haryana",13,NA,Under Construction,"['Sector 55-56 Metro Station', 'Airia Mall', '...",Pareena mi casa is one of the most popular des...,[],NaN,"['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."

In [45]:
df.insert(loc=4,column='Area',value=round((df['price(cr)']/df['price_per_sqft'])*10000000))
df.insert(loc=2,column='property_type',value='flat')
df.sample(5)

,property_name,society,property_type,price(cr),price_per_sqft,Area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1232,2 BHK Flat in Sector 113 Gurgaon,La Vida by Tata Housing,flat,1.32,10344.0,1276.0,Super Built up area 1276(118.54 sq.m.)Built Up...,2,2,2,Not available,"Sector 113 Gurgaon , Gurgaon, Haryana",3,North-East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",This lovely 2 bhk apartment/flat in sector 113...,"['2 Geyser', 'No AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
47,2 BHK Flat in Sector 106 Gurgaon,Paras Dews,flat,1.05,7581.0,1385.0,Carpet area: 1385 (128.67 sq.m.),2,2,2,Not available,"Sector 106 Gurgaon, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",It's on main dwarka expressway. Very close to ...,"['3 Fan', '2 Geyser', '7 Light', '3 AC', 'No B...","['Security / Fire Alarm', 'Power Back-up', 'In...",NaN
448,4 BHK Flat in Sector 54 Gurgaon,La Lagune,flat,6.75,21360.0,3160.0,Super Built up area 3160(293.57 sq.m.)Built Up...,4,6,3+,Servant Room,"La Lagune, Sector 54 Gurgaon, Gurgaon, Haryana",11,East,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Ardee Mall'...",Located in the popular residential address of ...,"['5 Wardrobe', '8 Fan', '5 Geyser', '1 Stove',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
1083,4 BHK Flat in Sector 69 Gurgaon,Tulip Violet,flat,1.80,8955.0,2010.0,Super Built up area 2010(186.74 sq.m.),4,4,2,Pooja Room,"A7 908, Sector 69 Gurgaon, Gurgaon, Haryana",9,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This 4 bhk apartment is available for sale in ...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
113,2 BHK Flat in Sector 65 Gurgaon,MM Skycity,flat,2.10,16030.0,1310.0,Super Built up area 1310(121.7 sq.m.),2,2,2,Not available,"4302, Sector 65 Gurgaon, Gurgaon, Haryana",43,NA,Within 6 months,"['Sector 55 Metro Station', 'Eros City Square'...",Ample sunlight\nDowntown\nSuper luxury\nWalk t...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [46]:
df.to_csv('../data/processed/flats_cleaned.csv', index=False)