In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/houses.csv')
print(df.shape)
df.head()

(1044, 21)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,...,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,...,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,...,"Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,...,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,...,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,...,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   str
 1   link             1044 non-null   str
 2   society          453 non-null    str
 3   price            968 non-null    str
 4   rate             1005 non-null   str
 5   area             1044 non-null   str
 6   areaWithType     987 non-null    str
 7   bedRoom          987 non-null    str
 8   bathroom         987 non-null    str
 9   balcony          987 non-null    str
 10  additionalRoom   589 non-null    str
 11  address          1031 non-null   str
 12  noOfFloor        967 non-null    str
 13  facing           674 non-null    str
 14  agePossession    987 non-null    str
 15  nearbyLocations  913 non-null    str
 16  description      1036 non-null   str
 17  furnishDetails   743 non-null    str
 18  features         674 non-null    str
 19  rating           907 non-null    str
 20  property_id      1036 non-null   str
dtypes: str(21)
memory usage: 2.0 MB

In [4]:
df.duplicated().sum()

np.int64(13)

In [5]:
df = df.drop_duplicates()
df.shape

(1031, 21)

In [6]:
df.drop(columns=['link','property_id'],inplace=True)

In [7]:
df.sample()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
216,8 Bedroom House for sale in Sector 56 Gurgaon,NaN,7.25 Crore,"₹ 29,336/sq.ft.",(253 sq.m.) Plot Area,Plot area 303(253.35 sq.m.),8 Bedrooms,8 Bathrooms,3+ Balconies,NaN,"Sector 56 Gurgaon, Gurgaon, Haryana",0 Floors,North-East,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...","The property is located in sector 56, next to ...","['15 Fan', '15 Light', '1 Modular Kitchen', 'N...","['High Ceiling Height', 'Natural Light', 'Airy...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [8]:
df['society'].value_counts()

society
Emaar MGF Marbella                     26
International City by SOBHA Phase 2    26
Vipul Tatvam Villa                     24
International City by Sobha Phase 1    23
Unitech Uniworld Resorts               13
                                       ..
Ansal Sushant Lok 2                     1
Godrej Meridien                         1
Sector 57 Huda                          1
Huda                                    1
Huda Floor                              1
Name: count, Length: 185, dtype: int64

In [9]:
df['society'] = df['society'].str.replace(r'\d+(\.\d+)?\s*★?', '', regex=True).str.strip()

In [10]:
df['society'].isnull().sum()

np.int64(586)

In [11]:
df.fillna({'society':'Independent'},inplace=True)
df.sample(5)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
717,6 Bedroom House for sale in DLF Phase 1,DLF City Plots,18 Crore,"₹ 39,841/sq.ft.",(420 sq.m.) Plot Area,Plot area 502(419.74 sq.m.),6 Bedrooms,6 Bathrooms,2 Balconies,"Pooja Room,Servant Room,Others","Abc108, DLF Phase 1, Gurgaon, Haryana",3 Floors,North,10+ Year Old,"['Phase 2 Metro Station', 'Grand Mall', 'Jacar...",Beautifully well maintained kothi on sale in d...,"['22 Wardrobe', '8 Fan', '1 Exhaust Fan', '6 G...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1025,6 Bedroom House for sale in Sector 17 Gurgaon,IFFCO Nagar and B RWA,2.98 Crore,"₹ 20,566/sq.ft.",(135 sq.m.) Plot Area,Plot area 161(134.62 sq.m.),6 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room","Iffco Chowk, Sector 17 Gurgaon, Gurgaon, Haryana",3 Floors,East,1 to 5 Year Old,"['Iffco chowk metro station', 'Mg road metro s...",Available very good residential property for s...,[],"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
194,3 Bedroom House for sale in Ashok Vihar,Independent,90 Lac,"₹ 80,357/sq.ft.",(10 sq.m.) Built-up Area,Built Up area: 112 (10.41 sq.m.),3 Bedrooms,3 Bathrooms,No Balcony,NaN,"Ashok Vihar, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,Best in class property available at ashok viha...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
752,4 Bedroom House for sale in DLF Phase 3,DLF Floors Phase,3.51 Crore,"₹ 12,342/sq.ft.",(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room,Store Room,Pooja Room","DLF Phase 3, Gurgaon, Haryana",4 Floors,East,Oct 2023,"['Dlf phase 3 metro station', 'Guru dronachary...",All 4 floors available for sale (3.51 cr. Per ...,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
567,10 Bedroom House for sale in Rajiv Chowk,Hans Enclave,2 Crore,"₹ 10,582/sq.ft.",(176 sq.m.) Built-up Area,Built Up area: 210 (175.59 sq.m.),10 Bedrooms,10 Bathrooms,3 Balconies,NaN,"Rajiv Chowk, Gurgaon, Haryana",3 Floors,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Hdfc...",I have a house/villa available for sale in raj...,NaN,NaN,"['Environment3.5 out of 5', 'Lifestyle4 out of..."

In [12]:
df['price'].value_counts()

price
3.5 Crore     19
5.5 Crore     17
6.5 Crore     16
6 Crore       14
5 Crore       13
              ..
3.8 Crore      1
7.45 Crore     1
7.42 Crore     1
6.09 Crore     1
2.98 Crore     1
Name: count, Length: 302, dtype: int64

In [13]:
df['price'].isnull().sum()

np.int64(76)

In [14]:
df[df['price'].isnull()]

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
47,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,NaN,(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","14a, Sector 66 Gurgaon, Gurgaon, Haryana",3 Floors,East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Excellent location, 24 meter wide road facing ...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '15 L...","['Centrally Air Conditioned', 'Water purifier'...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
62,5 Bedroom House for sale in Sector 109 Gurgaon,International City by SOBHA Phase,NaN,"₹ 13,622/sq.ft.",(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
63,4 Bedroom House for sale in Sector 109 Gurgaon,International City by SOBHA Phase,NaN,"₹ 13,909/sq.ft.",(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
66,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 16,058/sq.ft.",(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
67,4 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,"₹ 16,058/sq.ft.",(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,6 Bedroom House for sale in Sector 22 Gurgaon,Saksham Welfare Association,NaN,"₹ 19,645/sq.ft.",(220 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
920,5 Bedroom House for sale in DLF Phase 2,Independent,NaN,NaN,(420 sq.m.) Plot Area,Plot area 502(419.74 sq.m.)Built Up area: 450 ...,5 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2 Floors,West,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...",Dlf phase 2 very prime location. This villa we...,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1003,5 Bedroom House for sale in Sector 33 Gurgaon,Unitech Uniworld Resorts,NaN,NaN,(435 sq.m.) Plot Area,Plot area 520(434.79 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,"Servant Room,Store Room","A-898, Sector 33 Gurgaon, Gurgaon, Haryana",4 Floors,West,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",5 bhk 520 sqyd villas available at unitech uni...,"['5 Wardrobe', '15 Fan', '1 Exhaust Fan', '5 G...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1023,4 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,NaN,(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.)Built Up area: 6500...,4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Sector 66 Gurgaon, Gurgaon, Haryana",3 Floors,North,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This is 350 sq.Yd villa in the heart of the ci...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1024,5 Bedroom House for sale in Sector 66 Gurgaon,Emaar MGF Marbella,NaN,NaN,(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.),5 Bedrooms,5 Bathrooms,3 Balconies,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."

In [15]:
df = df.dropna(subset=['price'])
df['price'].isnull().sum()

np.int64(0)

In [16]:
df[df['price'] == 'Price on Request']

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
260,2 Bedroom House for sale in Sector 8 Gurgaon,Independent,Price on Request,NaN,(74 sq.m.) Built-up Area,Built Up area: 800 (74.32 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 8 Gurgaon, Gurgaon, Haryana",1 Floors,NaN,undefined,NaN,"1 bath, semi-Furnished, at sector 8 location g...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
261,3 Bedroom House for sale in Dharam Colony,Independent,Price on Request,NaN,(93 sq.m.) Carpet Area,Carpet area: 1000 (92.9 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Dharam Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, at dharam colony location...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
290,5 Bedroom House for sale in Laxman Vihar,Independent,Price on Request,NaN,(167 sq.m.) Built-up Area,Built Up area: 1800 (167.23 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,NaN,"Phase 2, Laxman Vihar, Gurgaon, Haryana",2 Floors,North,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","8 bath, unfurnished, overlooking main road, no...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
291,3 Bedroom House for sale in Laxman Vihar,Independent,Price on Request,NaN,(223 sq.m.) Built-up Area,Built Up area: 2400 (222.97 sq.m.)Carpet area:...,3 Bedrooms,4 Bathrooms,2 Balconies,NaN,"1248 B, Near Hanuman Mandir, Laxman Vihar, Gur...",2 Floors,NaN,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","4 bath, unfurnished, 1st floor (Of 2), 1 side ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
355,7 Bedroom House for sale in Rajendra Park,Independent,Price on Request,NaN,(585 sq.m.) Built-up Area,Built Up area: 700 (585.29 sq.m.),7 Bedrooms,6 Bathrooms,3 Balconies,NaN,"Rajendra Park, Gurgaon, Haryana",4 Floors,NaN,5 to 10 Year Old,NaN,"6 bath, furnished, 2 side open, at rajendra pa...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
384,3 Bedroom House for sale in Ansal Plaza,Independent,Price on Request,NaN,(40 sq.m.) Carpet Area,Carpet area: 429 (39.86 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Ansal Plaza, Sector 23, Ansal Plaza, Gurgaon, ...",4 Floors,NaN,undefined,NaN,Best in class property available at ansal plaz...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
447,2 Bedroom House for sale in Sheetla Colony,Independent,Price on Request,NaN,(42 sq.m.) Plot Area,Plot area 50(41.81 sq.m.)Built Up area: 720 sq...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sheetla Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, semi-Furnished, at sheetla colony loca...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5..."
522,5 Bedroom House for sale in Surat Nagar,Independent,Price on Request,NaN,(54 sq.m.) Built-up Area,Built Up area: 65 (54.35 sq.m.),5 Bedrooms,2 Bathrooms,No Balcony,NaN,"Surat Nagar Phase 2, Sector 104, Surat Nagar, ...",2 Floors,NaN,undefined,NaN,5bhk residential house for resale in surat nag...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5..."
548,2 Bedroom House for sale in Dharam Colony Block E,Independent,Price on Request,NaN,(84 sq.m.) Built-up Area,Built Up area: 900 (83.61 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Dharam Colony Block E, Gurgaon, Haryana",1 Floors,NaN,undefined,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","1 bath, unfurnished, ground floor (Of 1), at d...",NaN,NaN,NaN
621,4 Bedroom House for sale in Madanpuri,Independent,Price on Request,NaN,(167 sq.m.) Carpet Area,Carpet area: 1800 (167.23 sq.m.),4 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Madanpuri, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 1 side open, at madan pur...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [17]:
df = df[df['price'] != 'Price on Request']

In [18]:
def convert_price(price):
    price = str(price).strip()
    if('Lac' in price):
        price = price.replace('Lac','').strip()
        return round(float(price)/100,2)
    
    elif('Crore' in price):
        price = price.replace('Crore','').strip()
        return round(float(price),2)
    else:
        pass

In [19]:
df['price'] = df['price'].apply(convert_price)

In [20]:
df.rename(columns={'price':'price(cr)'},inplace=True)

In [21]:
df.sample()

,property_name,society,price(cr),rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
155,4 Bedroom House for sale in Sector 31 Gurgaon,Independent,3.69,"₹ 23,699/sq.ft.",(145 sq.m.) Plot Area,Plot area 173(144.65 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,"Study Room,Servant Room,Pooja Room","Sector 31 Gurgaon, Gurgaon, Haryana",2 Floors,East,5 to 10 Year Old,"['Icici bank ATM', 'State bank of india ATM', ...",4 bhk must see. It is a value for money deal. ...,"['5 Wardrobe', '5 Bed', '1 Water Purifier', '4...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [22]:
df.rename(columns={'rate':'price_per_sqft'},inplace=True)
df.sample()

,property_name,society,price(cr),price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
622,3 Bedroom House for sale in Dharam Colony,Independent,0.7,"₹ 6,034/sq.ft.",(108 sq.m.) Plot Area,Plot area 1160(107.77 sq.m.),3 Bedrooms,3 Bathrooms,No Balcony,NaN,"Dharam Colony, Gurgaon, Haryana",1 Floors,North-East,1 to 5 Year Old,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","Green area, open space and safe and secure area","['2 Fan', '2 Light', '1 Chimney', 'No AC', 'No...","['Private Garden / Terrace', 'Water Storage', ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [23]:
df['price_per_sqft'] = df['price_per_sqft'].str.replace(r'(₹|/sq.ft.)','',regex=True).str.replace(',','').str.strip().astype(float)
df.sample(5)

,property_name,society,price(cr),price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
386,5 Bedroom House for sale in Sector 53 Gurgaon,Independent,4.65,17574.0,(246 sq.m.) Plot Area,Plot area 294(245.82 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,NaN,"Dlf Exclusive Floors, Suncity, Sector 54, Gurg...",1 Floors,NaN,5 to 10 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...",Looking to buy an independent house in gurgaon...,"['7 Fan', '5 Geyser', '8 Light', '8 AC', '1 Ch...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
868,10 Bedroom House for sale in South City 1,Unitech Palms South City,9.35,28858.0,(301 sq.m.) Plot Area,Plot area 3240(301.01 sq.m.)Built Up area: 750...,10 Bedrooms,10 Bathrooms,3+ Balconies,"Servant Room,Study Room","K-222, South City 1, Gurgaon, Haryana",4 Floors,North-East,5 to 10 Year Old,"['Huda city centre metro station', 'Hdfc ATM',...",Beautifully maintained 10 bhk villa built on 3...,"['6 Fan', '10 Light', '5 AC', '1 Modular Kitch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
540,4 Bedroom House for sale in Sohna Gurgaon Road,Independent,2.00,7479.0,(248 sq.m.) Built-up Area,Built Up area: 2674 (248.42 sq.m.),4 Bedrooms,3 Bathrooms,No Balcony,NaN,"Sohna Gurgaon Road, Sohna Gurgaon Road, Gurgao...",1 Floors,North,undefined,NaN,4bhk villa for resale in sohna gurgaon road so...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
826,4 Bedroom House for sale in Sector 86 Gurgaon,DLF New Town Heights,2.50,7827.0,(297 sq.m.) Plot Area,Plot area 3194(296.73 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Servant Room,Others","Th98, Sector 86 Gurgaon, Gurgaon, Haryana",4 Floors,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",Society is very beautiful around of trees gard...,"['7 Fan', '1 Exhaust Fan', '3 Geyser', '10 Lig...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
676,5 Bedroom House for sale in Sector 14 Gurgaon,Independent,4.15,18444.0,(209 sq.m.) Plot Area,Plot area 250(209.03 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,NaN,"Sector 14 Gurgaon, Gurgaon, Haryana",2 Floors,North-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",250 sqyds independent house for sale in sector...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [24]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     230
5 Bedrooms     183
3 Bedrooms     146
2 Bedrooms      87
6 Bedrooms      80
9 Bedrooms      44
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      30
12 Bedrooms     27
10 Bedrooms     21
16 Bedrooms     11
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
21 Bedrooms      1
20 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [25]:
df['bedRoom'].isnull().sum()

np.int64(0)

In [26]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype(int)

In [27]:
df.sample()

,property_name,society,price(cr),price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
207,5 Bedroom House for sale in Sector 72 Gurgaon,Spaze Privy,3.1,8486.0,(339 sq.m.) Plot Area,Plot area 3653(339.37 sq.m.),5,5 Bathrooms,3+ Balconies,NaN,"Sector 72, Sector 72 Gurgaon, Gurgaon, Haryana",21 Floors,NaN,1 to 5 Year Old,NaN,Penthouse is available for sale. It has covere...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4.5 out of 5', 'Lifestyle4.5 out ..."

In [28]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     225
3 Bathrooms     164
5 Bathrooms     132
2 Bathrooms     112
6 Bathrooms      82
1 Bathroom       64
9 Bathrooms      41
7 Bathrooms      37
8 Bathrooms      26
12 Bathrooms     21
10 Bathrooms     11
16 Bathrooms      7
13 Bathrooms      4
18 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [29]:
df['bathroom'].isnull().sum()

np.int64(0)

In [30]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype(int)
df.sample()

,property_name,society,price(cr),price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
129,5 Bedroom House for sale in Sector 109 Gurgaon,International City by SOBHA Phase,12.5,26667.0,(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),5,6,3 Balconies,"Pooja Room,Study Room,Servant Room,Store Room","252, Sector 109 Gurgaon, Gurgaon, Haryana",3 Floors,East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...","4 luxurious bedrooms, drawing / dining / kitch...","['7 Geyser', '12 AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [31]:
df['balcony'].value_counts()

balcony
3+ Balconies    352
2 Balconies     217
3 Balconies     158
No Balcony      114
1 Balcony       104
Name: count, dtype: int64

In [32]:
df['balcony'].isnull().sum()

np.int64(0)

In [33]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')
df.sample(5)

,property_name,society,price(cr),price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
569,5 Bedroom House for sale in Sector 86 Gurgaon,SS Omnia,0.42,84000.0,(5 sq.m.) Plot Area,Plot area 50(4.65 sq.m.),5,3,2,NaN,"Sector 86 Gurgaon, Gurgaon, Haryana",3 Floors,NaN,1 to 5 Year Old,"['Orris Community Center', 'Essar Petrol Pump'...",Looking for buyer to purchase our house/villa ...,[],NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
379,3 Bedroom House for sale in Rajendra Park,Independent,1.15,3285.0,(325 sq.m.) Carpet Area,Carpet area: 3500 (325.16 sq.m.),3,2,1,NaN,"Rajendra Park Block B, Sector 105, Rajendra Pa...",1 Floors,NaN,undefined,NaN,Best in class property available at rajendra p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
302,2 Bedroom House for sale in Shivpuri,Independent,2.00,11111.0,(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),2,2,1,NaN,"Gurgaon Sector -7, Shivpuri, Gurgaon, Haryana",2 Floors,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Arya...",Interested to sell independent house/villa.Pla...,"['2 Fan', 'No AC', 'No Bed', 'No Chimney', 'No...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
208,5 Bedroom House for sale in Jyoti Park,Independent,1.16,11717.0,(92 sq.m.) Carpet Area,Carpet area: 110 (91.97 sq.m.),5,4,2,NaN,"Jyoti Park, Sector 7, Jyoti Park, Gurgaon, Har...",1 Floors,North-East,undefined,NaN,"Square plot, airy atmosphere, property ventila...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
330,2 Bedroom House for sale in Madanpuri,Independent,0.95,21111.0,(42 sq.m.) Plot Area,Plot area 450(41.81 sq.m.),2,1,1,NaN,"Madanpuri, Gurgaon, Haryana",3 Floors,NaN,0 to 1 Year Old,"['Dev Man Kathuria Clinic', 'Dr. Madan Clinic'...",Recently constructed just a month old\nGround ...,"['1 Wardrobe', '3 Fan', '1 Exhaust Fan', '5 Li...","['Water Storage', 'Park']","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [34]:
df.fillna({'additionalRoom':'NA'},inplace=True)
df.sample(5)

,property_name,society,price(cr),price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
867,3 Bedroom House for sale in Sushant Lok Phase 2,Independent,1.64,10123.0,(151 sq.m.) Plot Area,Plot area 180(150.5 sq.m.),3,3,2,"Study Room,Servant Room","Block A, Sushant Lok Phase 2, Gurgaon, Haryana",4 Floors,South,0 to 1 Year Old,"['Mg road metro station', 'Iffco chowk metro s...","Brand new luxury floor with lift, stilt parkin...","['4 Wardrobe', '6 Fan', '11 Light', '1 Modular...","['High Ceiling Height', 'Water Storage', 'No o...","['Environment4 out of 5', 'Safety4 out of 5', ..."
732,6 Bedroom House for sale in DLF Phase 1,DLF City Plots,26.00,57206.0,(422 sq.m.) Plot Area,Plot area 505(422.24 sq.m.),6,7,3+,"Pooja Room,Study Room,Servant Room,Others","0000, DLF Phase 1, Gurgaon, Haryana",2 Floors,North-East,0 to 1 Year Old,"['Phase 2 Metro Station', 'Grand Mall', 'Jacar...",505 sq.Y 6 bhk luxury villa \nIn dlf phase 1\n...,"['12 Fan', '1 Exhaust Fan', '6 Geyser', '1 Sto...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
206,4 Bedroom House for sale in Sector 76 Gurgaon,Ninex City,1.75,6250.0,(260 sq.m.) Carpet Area,Carpet area: 2800 (260.13 sq.m.),4,4,0,NA,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",14 Floors,NaN,undefined,NaN,Ninex sec 76 is one of the best located projec...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
562,1 Bedroom House for sale in Sector 3A Gurgaon,Independent,0.55,7333.0,(70 sq.m.) Built-up Area,Built Up area: 750 (69.68 sq.m.),1,1,0,NA,"80 Gaj Indipendent House In Laxman Vihar, Laxm...",1 Floors,NaN,undefined,"['Chintapurni Mandir', 'State bank ATM', 'Prat...",A 6 bhk independent house for sale in sector 3...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
541,3 Bedroom House for sale in Vishnu Garden,Independent,0.74,7400.0,(93 sq.m.) Built-up Area,Built Up area: 1000 (92.9 sq.m.),3,3,0,NA,"Vishnu Garden, Sector 105, Vishnu Garden, Gurg...",2 Floors,NaN,undefined,NaN,3bhk residential house for resale in vishnu ga...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."

In [35]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [36]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0)
df.sample(5)

,property_name,society,price(cr),price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
736,5 Bedroom House for sale in Sector 50 Gurgaon,SS Hibiscus,12.25,20940.0,(543 sq.m.) Plot Area,Plot area 5850(543.48 sq.m.),5,7,3+,"Pooja Room,Study Room,Servant Room,Others","A-23, Sector 50 Gurgaon, Gurgaon, Haryana",1,South-East,1 to 5 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",Rare inventory \nSs hibiscus villa \n650 yards...,"['1 Water Purifier', '1 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
490,4 Bedroom House for sale in Sector 6 Gurgaon,Bhim Nagar Society,0.40,2500.0,(149 sq.m.) Built-up Area,Built Up area: 1600 (148.64 sq.m.)Carpet area:...,4,2,2,NA,"Sector 6, Sector 6 Gurgaon, Gurgaon, Haryana",1,East,undefined,"['Dental Hospital', 'Sercare Clinic', 'Promla ...",4bhk residential house for resale in bhim naga...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
365,5 Bedroom House for sale in Ashok Vihar Phase 2,Independent,1.10,10000.0,(102 sq.m.) Built-up Area,Built Up area: 1100 (102.19 sq.m.)Carpet area:...,5,4,2,NA,"Ashok Vihar Phase 2, Delhi Gurgaon Expressway,...",1,East,undefined,NaN,Two side open house near by all facilities ash...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
669,4 Bedroom House for sale in Sushant Lok Phase 2,Independent,1.45,241666.0,(6 sq.m.) Plot Area,Plot area 60(5.57 sq.m.),4,4,3+,Store Room,"Sushant Lok Phase 2, Gurgaon, Haryana",4,East,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...",A property can be unique because of it's layou...,"['1 Wardrobe', 'No AC', 'No Bed', 'No Chimney'...","['Private Garden / Terrace', 'Water purifier',...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
190,4 Bedroom House for sale in Shivaji Nagar,Not Applicable,2.20,12222.0,(167 sq.m.) Plot Area,Plot area 1800(167.23 sq.m.),4,3,2,"Pooja Room,Study Room",NaN,1,South,10+ Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Hdfc...",We are proud owners of house/villa available f...,[],"['Private Garden / Terrace', 'Park', 'Visitor ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [37]:
df.fillna({'facing':'NA'},inplace=True)
df.sample(5)

,property_name,society,price(cr),price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
721,7 Bedroom House for sale in Sector 22 Gurgaon,Independent,4.75,20068.0,(220 sq.m.) Plot Area,Plot area 263(219.9 sq.m.)Built Up area: 261 s...,7,5,3+,"Pooja Room,Others","Sector 22 Gurgaon, Gurgaon, Haryana",3,South-West,10+ Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'R...",Basement plus 2 story of independent house for...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
879,4 Bedroom House for sale in Sushant Lok Phase 1,Sushant Lok Builder Floors,2.45,7756.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.)Built Up area: 540 sq...,4,4,3+,"Pooja Room,Study Room,Servant Room,Others","Sushant Lok Phase 1, Gurgaon, Haryana",3,West,5 to 10 Year Old,"['Huda city centre metro station', 'New Life C...",This is a 60 square yard(Pair) property\nMeans...,"['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Private Garden / Terrace', 'Water purifier',...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
940,4 Bedroom House for sale in DLF Phase 2,DLF City Plots Phase,6.30,35000.0,(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),4,4,3+,"Servant Room,Store Room","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2,East,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...",This is a four bedroom house in dlf phase - 2 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
598,1 Bedroom House for sale in Sector 39 Gurgaon,Independent,0.34,7555.0,(42 sq.m.) Built-up Area,Built Up area: 450 (41.81 sq.m.),1,1,1,NA,"Jharsa Village, Sector 39, Gurgaon, Sector 39 ...",1,NA,undefined,"['Rajiv Chowk Mosque', 'State bank of india AT...",1 bhk independent house for sale in gurgaon. T...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
971,4 Bedroom House for sale in Sector 15 Part 2,Independent,1.45,12393.0,(109 sq.m.) Plot Area,Plot area 130(108.7 sq.m.)Built Up area: 130 s...,4,4,2,Others,"Patel Nagar 525, Sector 15 Part 2, Gurgaon, Ha...",2,North,10+ Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...",House for sale 130 sqyard old house patel naga...,NaN,"['Maintenance Staff', 'Water Storage']","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [38]:
df.drop(columns=['area'],inplace=True)
df.insert(4, 'Area', round((df['price(cr)'] / df['price_per_sqft']) * 10000000))
df.sample()

,property_name,society,price(cr),price_per_sqft,Area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
523,"9 Bedroom House for sale in Gurgaon, Delhi NCR",Independent,1.5,16667.0,900.0,Carpet area: 900 (83.61 sq.m.),9,3,3+,NA,"Gurgaon, Delhi NCR, Gurgaon, Haryana",3,NA,undefined,NaN,9bhk residential house for resale in at gurgao...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN

In [39]:
df.insert(loc=2,column='property_type',value='house')
df.sample()

,property_name,society,property_type,price(cr),price_per_sqft,Area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
450,9 Bedroom House for sale in Sector 52 Gurgaon,Ardee City,house,5.5,183333.0,300.0,Plot area 300(27.87 sq.m.),9,9,3+,"Pooja Room,Servant Room,Others","Sector 52 Gurgaon, Gurgaon, Haryana",3,South,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Hanuman Mandir'...",Brokers please excuse 9 bedroom house built ar...,"['21 Fan', '1 Exhaust Fan', '9 Geyser', '10 AC...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [40]:
df.to_csv('../data/processed/house_cleaned.csv',index=False)